//Create a function to generate random integer numbers within a given range
function range(min, max) {
    return Math.floor(Math.random() * (max - min + 1) + min);
}

//Create a new folder
var idMk = charIDToTypeID( "Mk  " );
    var desc235 = new ActionDescriptor();
    var idnull = charIDToTypeID( "null" );
        var ref1 = new ActionReference();
        var idlayerSection = stringIDToTypeID( "layerSection" );
        ref1.putClass( idlayerSection );
    desc235.putReference( idnull, ref1 );
    var idlayerSectionStart = stringIDToTypeID( "layerSectionStart" );
    desc235.putInteger( idlayerSectionStart, 2 );
    var idlayerSectionEnd = stringIDToTypeID( "layerSectionEnd" );
    desc235.putInteger( idlayerSectionEnd, 3 );
    var idNm = charIDToTypeID( "Nm  " );
    desc235.putString( idNm, "World Map" );
executeAction( idMk, desc235, DialogModes.NO );

var idsetd = charIDToTypeID( "setd" );
    var desc239 = new ActionDescriptor();
    var idnull = charIDToTypeID( "null" );
        var ref2 = new ActionReference();
        var idLyr = charIDToTypeID( "Lyr " );
        var idOrdn = charIDToTypeID( "Ordn" );
        var idTrgt = charIDToTypeID( "Trgt" );
        ref2.putEnumerated( idLyr, idOrdn, idTrgt );
    desc239.putReference( idnull, ref2 );
    var idT = charIDToTypeID( "T   " );
        var desc240 = new ActionDescriptor();
        var idNm = charIDToTypeID( "Nm  " );
        desc240.putString( idNm, "World Layer" );
    var idLyr = charIDToTypeID( "Lyr " );
    desc239.putObject( idT, idLyr, desc240 );
executeAction( idsetd, desc239, DialogModes.NO );

//Create a new layer
var idMk = charIDToTypeID( "Mk  " );
    var desc244 = new ActionDescriptor();
    var idnull = charIDToTypeID( "null" );
        var ref3 = new ActionReference();
        var idLyr = charIDToTypeID( "Lyr " );
        ref3.putClass( idLyr );
    desc244.putReference( idnull, ref3 );
    var idLyrI = charIDToTypeID( "LyrI" );
    desc244.putInteger( idLyrI, 4 );
executeAction( idMk, desc244, DialogModes.NO );

var idsetd = charIDToTypeID( "setd" );
    var desc246 = new ActionDescriptor();
    var idnull = charIDToTypeID( "null" );
        var ref4 = new ActionReference();
        var idLyr = charIDToTypeID( "Lyr " );
        var idOrdn = charIDToTypeID( "Ordn" );
        var idTrgt = charIDToTypeID( "Trgt" );
        ref4.putEnumerated( idLyr, idOrdn, idTrgt );
    desc246.putReference( idnull, ref4 );
    var idT = charIDToTypeID( "T   " );
        var desc247 = new ActionDescriptor();
        var idNm = charIDToTypeID( "Nm  " );
        desc247.putString( idNm, "World Map" );
    var idLyr = charIDToTypeID( "Lyr " );
    desc246.putObject( idT, idLyr, desc247 );
executeAction( idsetd, desc246, DialogModes.NO );

//Render 'Clouds' a random amount of times
var i;
for (i=0;i<range(1, 50);i++) {
    var idClds = charIDToTypeID( "Clds" );
        var desc253 = new ActionDescriptor();
    executeAction( idClds, desc253, DialogModes.NO );
}

//Render 'Difference Clouds' a random amount of times
var i;
for (i=0;i<range(1, 50);i++) {
    var idDfrC = charIDToTypeID( "DfrC" );
        var desc259 = new ActionDescriptor();
    executeAction( idDfrC, desc259, DialogModes.NO );
}

//Add a 'Posterize' layer
var idMk = charIDToTypeID( "Mk  " );
    var desc274 = new ActionDescriptor();
    var idnull = charIDToTypeID( "null" );
        var ref5 = new ActionReference();
        var idAdjL = charIDToTypeID( "AdjL" );
        ref5.putClass( idAdjL );
    desc274.putReference( idnull, ref5 );
    var idUsng = charIDToTypeID( "Usng" );
        var desc275 = new ActionDescriptor();
        var idType = charIDToTypeID( "Type" );
            var desc276 = new ActionDescriptor();
            var idLvls = charIDToTypeID( "Lvls" );
            desc276.putInteger( idLvls, 12 );
        var idPstr = charIDToTypeID( "Pstr" );
        desc275.putObject( idType, idPstr, desc276 );
    var idAdjL = charIDToTypeID( "AdjL" );
    desc274.putObject( idUsng, idAdjL, desc275 );
executeAction( idMk, desc274, DialogModes.NO );

//Add a 'Layers' layer
var idMk = charIDToTypeID( "Mk  " );
    var desc294 = new ActionDescriptor();
    var idnull = charIDToTypeID( "null" );
        var ref7 = new ActionReference();
        var idAdjL = charIDToTypeID( "AdjL" );
        ref7.putClass( idAdjL );
    desc294.putReference( idnull, ref7 );
    var idUsng = charIDToTypeID( "Usng" );
        var desc295 = new ActionDescriptor();
        var idType = charIDToTypeID( "Type" );
            var desc296 = new ActionDescriptor();
            var idpresetKind = stringIDToTypeID( "presetKind" );
            var idpresetKindType = stringIDToTypeID( "presetKindType" );
            var idpresetKindDefault = stringIDToTypeID( "presetKindDefault" );
            desc296.putEnumerated( idpresetKind, idpresetKindType, idpresetKindDefault );
        var idLvls = charIDToTypeID( "Lvls" );
        desc295.putObject( idType, idLvls, desc296 );
    var idAdjL = charIDToTypeID( "AdjL" );
    desc294.putObject( idUsng, idAdjL, desc295 );
executeAction( idMk, desc294, DialogModes.NO );

var idsetd = charIDToTypeID( "setd" );
    var desc309 = new ActionDescriptor();
    var idnull = charIDToTypeID( "null" );
        var ref8 = new ActionReference();
        var idAdjL = charIDToTypeID( "AdjL" );
        var idOrdn = charIDToTypeID( "Ordn" );
        var idTrgt = charIDToTypeID( "Trgt" );
        ref8.putEnumerated( idAdjL, idOrdn, idTrgt );
    desc309.putReference( idnull, ref8 );
    var idT = charIDToTypeID( "T   " );
        var desc310 = new ActionDescriptor();
        var idpresetKind = stringIDToTypeID( "presetKind" );
        var idpresetKindType = stringIDToTypeID( "presetKindType" );
        var idpresetKindCustom = stringIDToTypeID( "presetKindCustom" );
        desc310.putEnumerated( idpresetKind, idpresetKindType, idpresetKindCustom );
        var idAdjs = charIDToTypeID( "Adjs" );
            var list8 = new ActionList();
                var desc311 = new ActionDescriptor();
                var idChnl = charIDToTypeID( "Chnl" );
                    var ref9 = new ActionReference();
                    var idChnl = charIDToTypeID( "Chnl" );
                    var idChnl = charIDToTypeID( "Chnl" );
                    var idCmps = charIDToTypeID( "Cmps" );
                    ref9.putEnumerated( idChnl, idChnl, idCmps );
                desc311.putReference( idChnl, ref9 );
                var idInpt = charIDToTypeID( "Inpt" );
                    var list9 = new ActionList();
                    list9.putInteger( 0 );
                    list9.putInteger( 86 );
                desc311.putList( idInpt, list9 );
            var idLvlA = charIDToTypeID( "LvlA" );
            list8.putObject( idLvlA, desc311 );
        desc310.putList( idAdjs, list8 );
    var idLvls = charIDToTypeID( "Lvls" );
    desc309.putObject( idT, idLvls, desc310 );
executeAction( idsetd, desc309, DialogModes.NO );

//Add a Gradient Map
var idMk = charIDToTypeID( "Mk  " );
    var desc320 = new ActionDescriptor();
    var idnull = charIDToTypeID( "null" );
        var ref10 = new ActionReference();
        var idAdjL = charIDToTypeID( "AdjL" );
        ref10.putClass( idAdjL );
    desc320.putReference( idnull, ref10 );
    var idUsng = charIDToTypeID( "Usng" );
        var desc321 = new ActionDescriptor();
        var idType = charIDToTypeID( "Type" );
            var desc322 = new ActionDescriptor();
            var idgradientsInterpolationMethod = stringIDToTypeID( "gradientsInterpolationMethod" );
            var idgradientInterpolationMethodType = stringIDToTypeID( "gradientInterpolationMethodType" );
            var idSmoo = charIDToTypeID( "Smoo" );
            desc322.putEnumerated( idgradientsInterpolationMethod, idgradientInterpolationMethodType, idSmoo );
            var idGrad = charIDToTypeID( "Grad" );
                var desc323 = new ActionDescriptor();
                var idNm = charIDToTypeID( "Nm  " );
                var idGrdF = charIDToTypeID( "GrdF" );
                var idGrdF = charIDToTypeID( "GrdF" );
                var idCstS = charIDToTypeID( "CstS" );
                desc323.putEnumerated( idGrdF, idGrdF, idCstS );
                var idIntr = charIDToTypeID( "Intr" );
                desc323.putDouble( idIntr, 4096.000000 );
                var idClrs = charIDToTypeID( "Clrs" );
                    var list11 = new ActionList();
                        var desc324 = new ActionDescriptor();
                        var idClr = charIDToTypeID( "Clr " );
                            var desc325 = new ActionDescriptor();
                            var idRd = charIDToTypeID( "Rd  " );
                            desc325.putDouble( idRd, 0.000000 );
                            var idGrn = charIDToTypeID( "Grn " );
                            desc325.putDouble( idGrn, 0.000000 );
                            var idBl = charIDToTypeID( "Bl  " );
                            desc325.putDouble( idBl, 0.000000 );
                        var idRGBC = charIDToTypeID( "RGBC" );
                        desc324.putObject( idClr, idRGBC, desc325 );
                        var idType = charIDToTypeID( "Type" );
                        var idClry = charIDToTypeID( "Clry" );
                        var idUsrS = charIDToTypeID( "UsrS" );
                        desc324.putEnumerated( idType, idClry, idUsrS );
                        var idLctn = charIDToTypeID( "Lctn" );
                        desc324.putInteger( idLctn, 0 );
                        var idMdpn = charIDToTypeID( "Mdpn" );
                        desc324.putInteger( idMdpn, 50 );
                    var idClrt = charIDToTypeID( "Clrt" );
                    list11.putObject( idClrt, desc324 );
                        var desc326 = new ActionDescriptor();
                        var idClr = charIDToTypeID( "Clr " );
                            var desc327 = new ActionDescriptor();
                            var idRd = charIDToTypeID( "Rd  " );
                            desc327.putDouble( idRd, 255.000000 );
                            var idGrn = charIDToTypeID( "Grn " );
                            desc327.putDouble( idGrn, 255.000000 );
                            var idBl = charIDToTypeID( "Bl  " );
                            desc327.putDouble( idBl, 255.000000 );
                        var idRGBC = charIDToTypeID( "RGBC" );
                        desc326.putObject( idClr, idRGBC, desc327 );
                        var idType = charIDToTypeID( "Type" );
                        var idClry = charIDToTypeID( "Clry" );
                        var idUsrS = charIDToTypeID( "UsrS" );
                        desc326.putEnumerated( idType, idClry, idUsrS );
                        var idLctn = charIDToTypeID( "Lctn" );
                        desc326.putInteger( idLctn, 4096 );
                        var idMdpn = charIDToTypeID( "Mdpn" );
                        desc326.putInteger( idMdpn, 50 );
                    var idClrt = charIDToTypeID( "Clrt" );
                    list11.putObject( idClrt, desc326 );
                desc323.putList( idClrs, list11 );
                var idTrns = charIDToTypeID( "Trns" );
                    var list12 = new ActionList();
                        var desc328 = new ActionDescriptor();
                        var idOpct = charIDToTypeID( "Opct" );
                        var idPrc = charIDToTypeID( "#Prc" );
                        desc328.putUnitDouble( idOpct, idPrc, 100.000000 );
                        var idLctn = charIDToTypeID( "Lctn" );
                        desc328.putInteger( idLctn, 0 );
                        var idMdpn = charIDToTypeID( "Mdpn" );
                        desc328.putInteger( idMdpn, 50 );
                    var idTrnS = charIDToTypeID( "TrnS" );
                    list12.putObject( idTrnS, desc328 );
                        var desc329 = new ActionDescriptor();
                        var idOpct = charIDToTypeID( "Opct" );
                        var idPrc = charIDToTypeID( "#Prc" );
                        desc329.putUnitDouble( idOpct, idPrc, 100.000000 );
                        var idLctn = charIDToTypeID( "Lctn" );
                        desc329.putInteger( idLctn, 4096 );
                        var idMdpn = charIDToTypeID( "Mdpn" );
                        desc329.putInteger( idMdpn, 50 );
                    var idTrnS = charIDToTypeID( "TrnS" );
                    list12.putObject( idTrnS, desc329 );
                desc323.putList( idTrns, list12 );
            var idGrdn = charIDToTypeID( "Grdn" );
            desc322.putObject( idGrad, idGrdn, desc323 );
        var idGdMp = charIDToTypeID( "GdMp" );
        desc321.putObject( idType, idGdMp, desc322 );
    var idAdjL = charIDToTypeID( "AdjL" );
    desc320.putObject( idUsng, idAdjL, desc321 );
executeAction( idMk, desc320, DialogModes.NO );

//Change it's colors
var idsetd = charIDToTypeID( "setd" );
    var desc372 = new ActionDescriptor();
    var idnull = charIDToTypeID( "null" );
        var ref11 = new ActionReference();
        var idAdjL = charIDToTypeID( "AdjL" );
        var idOrdn = charIDToTypeID( "Ordn" );
        var idTrgt = charIDToTypeID( "Trgt" );
        ref11.putEnumerated( idAdjL, idOrdn, idTrgt );
    desc372.putReference( idnull, ref11 );
    var idT = charIDToTypeID( "T   " );
        var desc373 = new ActionDescriptor();
        var idGrad = charIDToTypeID( "Grad" );
            var desc374 = new ActionDescriptor();
            var idNm = charIDToTypeID( "Nm  " );
            var idGrdF = charIDToTypeID( "GrdF" );
            var idGrdF = charIDToTypeID( "GrdF" );
            var idCstS = charIDToTypeID( "CstS" );
            desc374.putEnumerated( idGrdF, idGrdF, idCstS );
            var idIntr = charIDToTypeID( "Intr" );
            desc374.putDouble( idIntr, 4096.000000 );
            var idClrs = charIDToTypeID( "Clrs" );
                var list14 = new ActionList();
                    var desc375 = new ActionDescriptor();
                    var idClr = charIDToTypeID( "Clr " );
                        var desc376 = new ActionDescriptor();
                        var idRd = charIDToTypeID( "Rd  " );
                        desc376.putDouble( idRd, 65.998993 );
                        var idGrn = charIDToTypeID( "Grn " );
                        desc376.putDouble( idGrn, 81.998749 );
                        var idBl = charIDToTypeID( "Bl  " );
                        desc376.putDouble( idBl, 149.001617 );
                    var idRGBC = charIDToTypeID( "RGBC" );
                    desc375.putObject( idClr, idRGBC, desc376 );
                    var idType = charIDToTypeID( "Type" );
                    var idClry = charIDToTypeID( "Clry" );
                    var idUsrS = charIDToTypeID( "UsrS" );
                    desc375.putEnumerated( idType, idClry, idUsrS );
                    var idLctn = charIDToTypeID( "Lctn" );
                    desc375.putInteger( idLctn, 0 );
                    var idMdpn = charIDToTypeID( "Mdpn" );
                    desc375.putInteger( idMdpn, 50 );
                var idClrt = charIDToTypeID( "Clrt" );
                list14.putObject( idClrt, desc375 );
                    var desc377 = new ActionDescriptor();
                    var idClr = charIDToTypeID( "Clr " );
                        var desc378 = new ActionDescriptor();
                        var idRd = charIDToTypeID( "Rd  " );
                        desc378.putDouble( idRd, 223.996582 );
                        var idGrn = charIDToTypeID( "Grn " );
                        desc378.putDouble( idGrn, 225.996552 );
                        var idBl = charIDToTypeID( "Bl  " );
                        desc378.putDouble( idBl, 65.998993 );
                    var idRGBC = charIDToTypeID( "RGBC" );
                    desc377.putObject( idClr, idRGBC, desc378 );
                    var idType = charIDToTypeID( "Type" );
                    var idClry = charIDToTypeID( "Clry" );
                    var idUsrS = charIDToTypeID( "UsrS" );
                    desc377.putEnumerated( idType, idClry, idUsrS );
                    var idLctn = charIDToTypeID( "Lctn" );
                    desc377.putInteger( idLctn, 1106 );
                    var idMdpn = charIDToTypeID( "Mdpn" );
                    desc377.putInteger( idMdpn, 50 );
                var idClrt = charIDToTypeID( "Clrt" );
                list14.putObject( idClrt, desc377 );
                    var desc379 = new ActionDescriptor();
                    var idClr = charIDToTypeID( "Clr " );
                        var desc380 = new ActionDescriptor();
                        var idRd = charIDToTypeID( "Rd  " );
                        desc380.putDouble( idRd, 77.998810 );
                        var idGrn = charIDToTypeID( "Grn " );
                        desc380.putDouble( idGrn, 185.001068 );
                        var idBl = charIDToTypeID( "Bl  " );
                        desc380.putDouble( idBl, 39.999390 );
                    var idRGBC = charIDToTypeID( "RGBC" );
                    desc379.putObject( idClr, idRGBC, desc380 );
                    var idType = charIDToTypeID( "Type" );
                    var idClry = charIDToTypeID( "Clry" );
                    var idUsrS = charIDToTypeID( "UsrS" );
                    desc379.putEnumerated( idType, idClry, idUsrS );
                    var idLctn = charIDToTypeID( "Lctn" );
                    desc379.putInteger( idLctn, 4096 );
                    var idMdpn = charIDToTypeID( "Mdpn" );
                    desc379.putInteger( idMdpn, 50 );
                var idClrt = charIDToTypeID( "Clrt" );
                list14.putObject( idClrt, desc379 );
            desc374.putList( idClrs, list14 );
            var idTrns = charIDToTypeID( "Trns" );
                var list15 = new ActionList();
                    var desc381 = new ActionDescriptor();
                    var idOpct = charIDToTypeID( "Opct" );
                    var idPrc = charIDToTypeID( "#Prc" );
                    desc381.putUnitDouble( idOpct, idPrc, 100.000000 );
                    var idLctn = charIDToTypeID( "Lctn" );
                    desc381.putInteger( idLctn, 0 );
                    var idMdpn = charIDToTypeID( "Mdpn" );
                    desc381.putInteger( idMdpn, 50 );
                var idTrnS = charIDToTypeID( "TrnS" );
                list15.putObject( idTrnS, desc381 );
                    var desc382 = new ActionDescriptor();
                    var idOpct = charIDToTypeID( "Opct" );
                    var idPrc = charIDToTypeID( "#Prc" );
                    desc382.putUnitDouble( idOpct, idPrc, 100.000000 );
                    var idLctn = charIDToTypeID( "Lctn" );
                    desc382.putInteger( idLctn, 4096 );
                    var idMdpn = charIDToTypeID( "Mdpn" );
                    desc382.putInteger( idMdpn, 50 );
                var idTrnS = charIDToTypeID( "TrnS" );
                list15.putObject( idTrnS, desc382 );
            desc374.putList( idTrns, list15 );
        var idGrdn = charIDToTypeID( "Grdn" );
        desc373.putObject( idGrad, idGrdn, desc374 );
    var idGdMp = charIDToTypeID( "GdMp" );
    desc372.putObject( idT, idGdMp, desc373 );
executeAction( idsetd, desc372, DialogModes.NO );